### ISSUE TITLE
Monero node not connectable over SSL

### ISSUE THREAD

**Issue by MoneroArbo** [cypherstack/stack_wallet#165]
Self signed SSL works when explicitly setting SSL on Cake and my understanding is that other wallets default to SSL and accept self signed certs as well. The default setup for monerod itself is to self sign certs afaik.

**edit:** self signed certs also work when connecting to LTC and BTC Electrum servers in Stack so I'd guess this is an unintentional inconsistency

One thing I might suggest that other wallets don't do, is to show a fingerprint when the certificate is self signed. This would let users manually authenticate.

From debug info:

```
HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: self signed certificate([handshake.cc:393](http://handshake.cc:393/)))
#0      _SecureFilterImpl._handshake (dart:io-patch/secure_socket_patch.dart:99)
#1      _SecureFilterImpl.handshake (dart:io-patch/secure_socket_patch.dart:142)
#2      _RawSecureSocket._secureHandshake (dart:io/secure_socket.dart:911)
#3      _RawSecureSocket._tryFilter (dart:io/secure_socket.dart:1040)
<asynchronous suspension>
```

**Comment by MoneroArbo** [comment]
Fixed in 1.5.16, now displays fingerprint for unsigned certs. wonderful!
