### ISSUE TITLE
Navigation Error after creating manual backup

### ISSUE THREAD

**Issue by danrmiller** [cypherstack/stack_wallet#223]
After creating a backup in Linux, stack wallet version 1.5.17 Build 89, a black bar saying Navigation Error comes up and the screen says "Error handling route, this is not supposed to happen. Try restarting the app."

```
flutter: BUILD: _SettingsMenuState
flutter: BUILD: _BackupRestoreSettings
flutter: BUILD: _BackupRestoreSettings
flutter: Directory: '/home/pigeons/Documents'
flutter: Directory: '/home/pigeons/Documents'
flutter: Log: [Info][2022-11-15 04:48:23.253Z]: Starting createStackWalletJSON...
flutter: Log: [Info][2022-11-15 04:48:23.264Z]: createStackWalletJSON awaiting DB.instance.mutex...
flutter: Log: [Info][2022-11-15 04:48:23.264Z]: ...createStackWalletJSON DB.instance.mutex acquired
flutter: Log: [Warning][2022-11-15 04:48:23.265Z]: SWB backing up nodes
flutter: Log: [Warning][2022-11-15 04:48:23.287Z]: SWB backing up prefs
flutter: Log: [Warning][2022-11-15 04:48:23.287Z]: SWB backing up addressbook
flutter: Log: [Warning][2022-11-15 04:48:23.287Z]: SWB backing up wallets
flutter: Log: [Warning][2022-11-15 04:48:23.292Z]: SWB backing up trades
flutter: Log: [Warning][2022-11-15 04:48:23.293Z]: SWB backing up trade notes
flutter: Log: [Info][2022-11-15 04:48:23.293Z]: createStackWalletJSON DB.instance.mutex released
flutter: Log: [Info][2022-11-15 04:48:23.294Z]: ...createStackWalletJSON complete
flutter: Log: [Info][2022-11-15 04:48:27.972Z]: File: '/home/pigeons/DocumentsDocuments/Stack_backups/stackbackup_2022_11_14_20_48_23.swb'
[ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Null check operator used on a null value
#0      State.setState (package:flutter/src/widgets/framework.dart:1129)
#1      _RestoreFromFileViewState.build.<anonymous closure> (package:stackwallet/pages/settings_views/global_settings_view/stack_backup_views/create_backup_view.dart:650)
<asynchronous suspension>

```

**Comment by ryleedavis** [comment]
Navigation error on manual backup should be fixed with build v1.5.18 (90)
