### ISSUE TITLE
Won't fully restore from swb backup file; stops on epic cash

### ISSUE THREAD

**Issue by danrmiller** [cypherstack/stack_wallet#226]
Staging branch on 4fb35be, android arm64-v8a

Trying to restore a swb backup created with version 1.5.17 it gets through some of the wallets and skips the rest with this error in the logs.

```
LogLevel.Fatal: Null check operator used on a null value #0      deleteEpicWallet (package:stackwallet/services/coins/epiccash/epiccash_wallet.dart:279)
<asynchronous suspension>
#1      WalletsService.deleteWallet (package:stackwallet/services/wallets_service.dart:381)
<asynchronous suspension>
#2      Wallets.load (package:stackwallet/services/wallets.dart:258)
<asynchronous suspension>
#3      _MaterialAppWithThemeState.load (package:stackwallet/main.dart:260)
<asynchronous suspension>
#4      _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:627)
<asynchronous suspension>
```

**Comment by julian-CStack** [comment]
Possible fix was applied a while ago and I'm currently unable to reproduce
