### ISSUE TITLE
`type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>'`when syncing with some servers

### ISSUE THREAD

**Issue by molecular** [cypherstack/stack_wallet#405]
Version 1.6.0

So I've been playing with the network settings, trying different servers I got from electron cash server list.

The following servers work without problem:

  * bitcoincash.stackwallet.com:50002 ssl
  * electrum.imaginary.cash:50002 ssl
  * fulcrum.criptolayer.net:50002 ssl

But with the following server:

  * fulcrum.fountainhead.cash:50002 ssl
 
There are problems: While `Test Connection` reports successfull ping, syncing fails around 40% or 60% and then stackwallet disconnects from that server.

Here's the log:

```
[Info][2023-03-06 10:22:36.148Z]: Periodic notifications update check
[Info][2023-03-06 10:22:39.815Z]: WalletSyncStatusChangedEvent fired in 83534a40-811a-11ed-b31c-6bcdcaf2d028 with arg newStatus = WalletSyncStatus.syncing
[Info][2023-03-06 10:22:39.820Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.0
[Info][2023-03-06 10:22:39.825Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.1
[Info][2023-03-06 10:22:40.107Z]: chain height: 782742
[Info][2023-03-06 10:22:40.111Z]: cached height: 1
[Info][2023-03-06 10:22:40.114Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.2
[Info][2023-03-06 10:22:40.212Z]: Number of txs for current change address { id: 21, walletId: 83534a40-811a-11ed-b31c-6bcdcaf2d028, value: bitcoincash:qpzffac0ajylthp52j8km9x8wtltr28t7vp9py83hp, publicKey: [2, 69, 204, 176, 53, 104, 117, 59, 137, 33, 237, 50, 137, 2, 34, 123, 88, 52, 80, 126, 34, 36, 242, 235, 229, 190, 212, 168, 110, 52, 73, 155, 168], derivationIndex: 4, type: p2pkh, subType: change, transactionsLength: 0 derivationPath: m/44'/145'/0'/1/4, otherData: null, }: 0
[Info][2023-03-06 10:22:40.216Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.3
[Info][2023-03-06 10:22:40.356Z]: Number of txs for current receiving address { id: 18, walletId: 83534a40-811a-11ed-b31c-6bcdcaf2d028, value: bitcoincash:qqmyw0e2a2660h3kuga00x3ysw7x35zhgg5ecsg60v, publicKey: [3, 28, 80, 64, 15, 189, 159, 65, 29, 202, 6, 127, 113, 46, 243, 154, 196, 93, 229, 26, 180, 37, 190, 33, 166, 142, 13, 213, 28, 103, 134, 125, 199], derivationIndex: 3, type: p2pkh, subType: receiving, transactionsLength: 0 derivationPath: m/44'/145'/0'/0/3, otherData: null, }: 0
[Info][2023-03-06 10:22:40.362Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.5
[Info][2023-03-06 10:22:40.366Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.6
[Info][2023-03-06 10:22:40.369Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.7
[Error][2023-03-06 10:22:40.478Z]: Output fetch unsuccessful: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      ElectrumX.batchRequest (package:stackwallet/electrumx_rpc/electrumx.dart:231)
<asynchronous suspension>
#1      ElectrumX.getBatchUTXOs (package:stackwallet/electrumx_rpc/electrumx.dart:482)
<asynchronous suspension>
#2      BitcoinCashWallet._updateUTXOs (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:1714)
<asynchronous suspension>
#3      BitcoinCashWallet.refresh (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:980)
<asynchronous suspension>
#4      Manager.refresh (package:stackwallet/services/coins/manager.dart:145)
<asynchronous suspension>

[Info][2023-03-06 10:22:40.483Z]: RefreshPercentChangedEvent fired on 83534a40-811a-11ed-b31c-6bcdcaf2d028 with percent (range of 0.0-1.0)= 0.8
[Error][2023-03-06 10:22:40.487Z]: _fetchHistory: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      ElectrumX.batchRequest (package:stackwallet/electrumx_rpc/electrumx.dart:231)
<asynchronous suspension>
#1      ElectrumX.getBatchHistory (package:stackwallet/electrumx_rpc/electrumx.dart:428)
<asynchronous suspension>
#2      BitcoinCashWallet._fetchHistory (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2027)
<asynchronous suspension>
#3      BitcoinCashWallet._refreshTransactions (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2083)
<asynchronous suspension>
#4      BitcoinCashWallet.refresh (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:984)
<asynchronous suspension>
#5      Manager.refresh (package:stackwallet/services/coins/manager.dart:145)
<asynchronous suspension>

[Info][2023-03-06 10:22:40.491Z]: NodeConnectionStatusChangedEvent fired in 83534a40-811a-11ed-b31c-6bcdcaf2d028 with arg newStatus = NodeConnectionStatus.disconnected
[Info][2023-03-06 10:22:40.494Z]: WalletSyncStatusChangedEvent fired in 83534a40-811a-11ed-b31c-6bcdcaf2d028 with arg newStatus = WalletSyncStatus.unableToSync
[Error][2023-03-06 10:22:40.498Z]: Caught exception in refreshWalletData(): type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      ElectrumX.batchRequest (package:stackwallet/electrumx_rpc/electrumx.dart:231)
<asynchronous suspension>
#1      ElectrumX.getBatchHistory (package:stackwallet/electrumx_rpc/electrumx.dart:428)
<asynchronous suspension>
#2      BitcoinCashWallet._fetchHistory (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2027)
<asynchronous suspension>
#3      BitcoinCashWallet._refreshTransactions (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2083)
<asynchronous suspension>
#4      BitcoinCashWallet.refresh (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:984)
<asynchronous suspension>
#5      Manager.refresh (package:stackwallet/services/coins/manager.dart:145)
<asynchronous suspension>

[Info][2023-03-06 10:22:40.501Z]: NodeConnectionStatusChangedEvent activated notifyListeners() in Manager instance 906599644 bch with: NodeConnectionStatus.disconnected
[Info][2023-03-06 10:22:40.710Z]: fetched fees: {fast: 1000, medium: 1000, slow: 1000, numberOfBlocksFast: 1, numberOfBlocksAverage: 5, numberOfBlocksSlow: 20}
[Info][2023-03-06 10:22:44.098Z]: This is the .swb content from intent: null
[Info][2023-03-06 10:23:05.101Z]: refreshIfThereIsNewData
[Info][2023-03-06 10:23:05.109Z]: notified unconfirmed transactions: [812aaa1c29e12ce9ccaaee7f77ef97f49ccf727c702571f6c6e75908549ffd27, 87c3904a8ba6f0bc4f25af77e5564285d56ac0b9eff79edc0c6478851fd0a31a, 82aeefac79b0b8dc1d94b2d2b10cfb880c2642f0b2c5b08d0ab4d08bd8917635, 6efe9c8d1555b027314f5d84d17f28c8944186e07d310d71bb1f47b0d94f5da1, b14b317283adfa56e920d9dd5c1a7c89b81d1d14d4b0c1df015ac72710719106, 3ab07e0d853a825974b71bd71a895787ab6af61179d7c79d21bf22cb185f1566, 43575a35859740d722df43f330799b91b532f54b4a971ac45c1421c649b82a79]
[Error][2023-03-06 10:23:05.237Z]: _fetchHistory: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      ElectrumX.batchRequest (package:stackwallet/electrumx_rpc/electrumx.dart:231)
<asynchronous suspension>
#1      ElectrumX.getBatchHistory (package:stackwallet/electrumx_rpc/electrumx.dart:428)
<asynchronous suspension>
#2      BitcoinCashWallet._fetchHistory (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2027)
<asynchronous suspension>
#3      BitcoinCashWallet.refreshIfThereIsNewData (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:775)
<asynchronous suspension>
#4      BitcoinCashWallet.refresh.<anonymous closure> (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:1004)
<asynchronous suspension>

[Info][2023-03-06 10:23:05.246Z]: Exception caught in refreshIfThereIsNewData: type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'List<dynamic>' in type cast
#0      ElectrumX.batchRequest (package:stackwallet/electrumx_rpc/electrumx.dart:231)
<asynchronous suspension>
#1      ElectrumX.getBatchHistory (package:stackwallet/electrumx_rpc/electrumx.dart:428)
<asynchronous suspension>
#2      BitcoinCashWallet._fetchHistory (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:2027)
<asynchronous suspension>
#3      BitcoinCashWallet.refreshIfThereIsNewData (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:775)
<asynchronous suspension>
#4      BitcoinCashWallet.refresh.<anonymous closure> (package:stackwallet/services/coins/bitcoincash/bitcoincash_wallet.dart:1004)
<asynchronous suspension>
```

**Comment by sneurlax** [comment]
This ought to be resolved.  @molecular can you try again?
