### ISSUE TITLE
Bug: Stack Wallet app window fails to render if Tor fails to select a random port

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/stack_wallet#675]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Today on Linux Desktop, Tor failed to select a random port.  The app just hung on a grey screen pre-loading-icon.

### Expected Behavior

Something else

### Reproduce Steps

Hard to reproduce--manually force it to fail to find a port to reproduce the behavior

### Environment

Ubuntu 20.04 Linux Desktop

**Comment by sneurlax** [comment]
Hit this again just now.
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Failed to get random unused port!
#0      Tor.start (package:tor_ffi_plugin/tor_ffi_plugin.dart:110:9)
<asynchronous suspension>
#1      TorService.start (package:stackwallet/services/tor_service.dart:74:7)
<asynchronous suspension>
#2      main (package:stackwallet/main.dart:179:5)
<asynchronous suspension>

```

**Comment by sneurlax** [comment]
This is no longer the case!  Tor can fail to start with this error but the UI doesn't indicate this issue.

**Comment by sneurlax** [comment]
Reproduced just now.
